#
# Just update APT cache + update all package when init server
#

---
- name: common | update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: common | update all packages to the latest version
  apt:
    name: "*"
    state: present

# Fix [WARNING]: Could not find aptitude. Using apt-get instead.
- name: common | install aptitude
  apt:
    name: aptitude
    state: present
