#
# Logrotate
#
---
- name: common | config global logrotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - r_common_based
    - r_common_logrotate
