#
# node_exporter: Exporter for machine metrics https://prometheus.io
# https://github.com/prometheus/node_exporter
#

---
- name: common | install node_exporter
  get_url:
    url: "{{ node_exporter_url }}"
    dest: "{{ node_exporter_file }}"
  tags:
    - r_common_based
    - r_common_node_exporter

- name: common | extract node_exporter.gz into /usr/src/build
  unarchive:
    src: "{{ node_exporter_file }}"
    dest: /usr/src/build
    remote_src: yes
  tags:
    - r_common_based
    - r_common_node_exporter

- name: common | copy node_exporter binary
  copy:
    src: "{{ node_exporter_src_bin  }}"
    dest: "{{ node_exporter_dest_bin  }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  tags:
    - r_common_based
    - r_common_node_exporter

- name: common | create node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present
  tags:
    - r_common_based
    - r_common_node_exporter

- name: common | create node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    create_home: no
    home: "/var/lib/{{ node_exporter_user }}"
    shell: /usr/sbin/nologin
    state: present
    group: "{{ node_exporter_group }}"
  tags:
    - r_common_based
    - r_common_node_exporter

- name: common | create node_exporter data dir
  file:
    path: "/var/lib/{{ node_exporter_user }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0755
  tags:
    - r_common_based
    - r_common_node_exporter

- name: common | copy node_exporter config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: 'node_exporter.service.j2', dest: '/etc/systemd/system/node_exporter.service' }
    - { src: 'node_exporter.j2', dest: '/etc/default/node_exporter' }
  notify:
    - systemd-reload
    - restart node_exporter service
  tags:
    - r_common_based
    - r_common_node_exporter
