#
# Config sshd service with notification + show header when connect
#

---
- name: common | update banner + motd
  template:
    src: motd.j2
    dest: /etc/motd-warning
    owner: root
    group: root
    mode: 0644
  tags:
    - r_common_based
    - r_common_sshd

- name: common | install figlet support header script
  apt:
    name: "figlet"
    state: present
  tags:
    - r_common_based
    - r_common_sshd

- name: common | update header script in profile.d
  template:
    src: 00-header.sh.j2
    dest: /etc/update-motd.d/00-header
    owner: root
    group: root
    mode: 0755
  tags:
    - r_common_based
    - r_common_sshd

- name: common | remove help text
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/update-motd.d/10-help-text
    - /etc/update-motd.d/51-cloudguest
  tags:
    - r_common_based
    - r_common_sshd

- name: common | config sshd service
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd service
  tags:
    - r_common_based
    - r_common_sshd
